server:
  port: 8933
  servlet:
    context-path: /api
spring:
  datasource:
    name: ShiroJwt
    url: jdbc:mysql://148.70.156.132:3306/smart_city_fhjy?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Qwas#$zx1278
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      connection-test-query: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss" #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期

mybatis:
  # Mybatis配置Mapper路径
  mapper-locations: classpath:mapper/*.xml
  # Mybatis配置Model类对应
  type-aliases-package: com.example.jm.Model

mapper:
  # 通用Mapper的insertSelective和updateByPrimaryKeySelective中是否判断字符串类型!=''
  not-empty: true

#配置日志
logging:
  #配置日志文件路径
  level:
    com:
      example:
        jm:
          mapper: debug
    org:
      springframework: info
      spring:
        springboot:
          mapper: info
      com:
        # example: info
        example: info

  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  #file: log\myspringboot.log

